version: "3.9"

services:
  application-service:
    build: ./application-service
    ports:
      - "3001:3001"

  order-service:
    build: ./order-service
    ports:
      - "8080:8080"

  patient-service:
    build: ./patient-service
    ports:
      - "3000:3000"
